/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario;

import javax.swing.JOptionPane;

/**
 *
 * @author achoc
 */
public class JControl extends javax.swing.JFrame {

    private Inventario Inv;

    /**
     * Creates new form JInventario
     */
    public JControl(Inventario Inv) {
        this.Inv = Inv;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jInputNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jInputDescripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jInputPrecio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jInputDescuento = new javax.swing.JTextField();
        jBoxCategoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButtonResolver = new javax.swing.JButton();
        jLabelTitle1 = new javax.swing.JLabel();
        jInputTitle1 = new javax.swing.JTextField();
        jLabelTitle2 = new javax.swing.JLabel();
        jInputTitle2 = new javax.swing.JTextField();
        jButtonResolver1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelStock = new javax.swing.JLabel();
        jInputStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelMontoConDesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTROL DE INVENTARIO");

        jLabel3.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel3.setText("Complete la información de los Productos");

        jLabel4.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel4.setText("Registre los Productos");

        jLabel5.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel5.setText("Nombre*");

        jInputNombre.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jInputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputNombreActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel6.setText("Descripcion");

        jInputDescripcion.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jInputDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputDescripcionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel7.setText("Precio");

        jInputPrecio.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jInputPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputPrecioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel8.setText("Descuento");

        jInputDescuento.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jInputDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputDescuentoActionPerformed(evt);
            }
        });

        jBoxCategoria.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrodomesticos", "Ropa", "Libros", "Deportes" }));
        jBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxCategoriaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel9.setText("Seleccione la categoria");

        jButtonResolver.setBackground(new java.awt.Color(0, 51, 153));
        jButtonResolver.setFont(new java.awt.Font("Product Sans", 1, 15)); // NOI18N
        jButtonResolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResolver.setText("Añadir Producto al Inventario");
        jButtonResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResolverActionPerformed(evt);
            }
        });

        jLabelTitle1.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabelTitle1.setText("Modelo");

        jInputTitle1.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jInputTitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputTitle1ActionPerformed(evt);
            }
        });

        jLabelTitle2.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabelTitle2.setText("Marca");

        jInputTitle2.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jInputTitle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputTitle2ActionPerformed(evt);
            }
        });

        jButtonResolver1.setBackground(new java.awt.Color(0, 51, 153));
        jButtonResolver1.setFont(new java.awt.Font("Product Sans", 1, 15)); // NOI18N
        jButtonResolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResolver1.setText("Ver Inventario de mis Productos");
        jButtonResolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResolver1ActionPerformed(evt);
            }
        });

        jLabelStock.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabelStock.setText("Stock");

        jInputStock.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jInputStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputStockActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel10.setText("Monto en Stock Sin Des");

        jLabelMonto.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabelMonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMonto.setText("0.0 Bs");
        jLabelMonto.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel11.setText("Monto en Stock Con Des");

        jLabelMontoConDesc.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabelMontoConDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMontoConDesc.setText("0.0 Bs");
        jLabelMontoConDesc.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                        .addComponent(jInputNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jInputTitle1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTitle1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jInputTitle2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTitle2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jInputDescripcion)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jInputPrecio)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jInputDescuento)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(32, 32, 32))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jInputStock, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                .addGap(29, 29, 29))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabelMontoConDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonResolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addComponent(jLabelMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10)))
                                    .addGap(6, 6, 6)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInputPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInputDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInputStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(jBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelTitle1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jInputTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelTitle2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jInputTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMontoConDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputNombreActionPerformed
        // TODO add your handling code here:
        //            String evaluacionFormateado = E.formato(evaluacion);
    }//GEN-LAST:event_jInputNombreActionPerformed

    private void jInputDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputDescripcionActionPerformed

    private void jInputPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputPrecioActionPerformed

    private void jInputDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputDescuentoActionPerformed

    private void jButtonResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverActionPerformed
        // TODO add your handling code here:
        String nombre = jInputNombre.getText();
        String descripcion = jInputDescripcion.getText();
        double precio = Double.parseDouble(jInputPrecio.getText());
        int descuento = Integer.parseInt(jInputDescuento.getText());
        int stock = Integer.parseInt(jInputStock.getText());
        String opcion = (String) jBoxCategoria.getSelectedItem();
        Object nuevo = new Object();
        switch (opcion) {
            case "Electrodomesticos":
                String text1 = jInputTitle1.getText();
                String text2 = jInputTitle2.getText();
                Electrodomesticos x1 = new Electrodomesticos(nombre, descripcion, precio, descuento, stock, opcion, text1, text2);
                nuevo = x1;
                break;
            case "Ropa":
                String text3 = jInputTitle1.getText();
                String text4 = jInputTitle2.getText();
                Ropa x2 = new Ropa(nombre, descripcion, precio, descuento, stock, opcion, text3, text4);
                nuevo = x2;
                break;
            case "Libros":
                String text5 = jInputTitle1.getText();
                Libro x3 = new Libro(nombre, descripcion, precio, descuento, stock, opcion, text5);
                nuevo = x3;
                break;
            case "Deportes":
                String text6 = jInputTitle1.getText();
                Deporte x4 = new Deporte(nombre, descripcion, precio, descuento, stock, opcion, text6);
                nuevo = x4;
                break;
        }
        Inv.registrar((Producto) nuevo);
        jLabelMonto.setText(Double.toString(Inv.CalcularPrecioTotal()));
        jLabelMontoConDesc.setText(Double.toString(Inv.CalcularPrecioTotalDes()));
    }//GEN-LAST:event_jButtonResolverActionPerformed

    private void jInputTitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputTitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputTitle1ActionPerformed

    private void jInputTitle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputTitle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputTitle2ActionPerformed

    private void jBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxCategoriaActionPerformed
        // TODO add your handling code here:
//        Mostramos los botones de acuerdo a la categoria
        String opcion = (String) jBoxCategoria.getSelectedItem();
        switch (opcion) {
            case "Electrodomesticos":
                jLabelTitle1.setText("Modelo");
                jLabelTitle2.setText("Marca");
                jLabelTitle2.setVisible(true);
                jInputTitle2.setVisible(true);
                break;
            case "Ropa":
                jLabelTitle1.setText("Material");
                jLabelTitle2.setText("Talla");
                jLabelTitle2.setVisible(true);
                jInputTitle2.setVisible(true);
                break;
            case "Libros":
                jLabelTitle1.setText("Autor");
                jLabelTitle2.setVisible(false);
                jInputTitle2.setVisible(false);
                break;
            case "Deportes":
                jLabelTitle1.setText("Disciplina");
                jLabelTitle2.setVisible(false);
                jInputTitle2.setVisible(false);
        }
    }//GEN-LAST:event_jBoxCategoriaActionPerformed

    private void jButtonResolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolver1ActionPerformed
        // TODO add your handling code here:
        JInventario vista = new JInventario(Inv);
        vista.setVisible(true);
    }//GEN-LAST:event_jButtonResolver1ActionPerformed

    private void jInputStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputStockActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBoxCategoria;
    private javax.swing.JButton jButtonResolver;
    private javax.swing.JButton jButtonResolver1;
    private javax.swing.JTextField jInputDescripcion;
    private javax.swing.JTextField jInputDescuento;
    private javax.swing.JTextField jInputNombre;
    private javax.swing.JTextField jInputPrecio;
    private javax.swing.JTextField jInputStock;
    private javax.swing.JTextField jInputTitle1;
    private javax.swing.JTextField jInputTitle2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelMontoConDesc;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
